-- Wygenerowano z lib/projects.ts i lib/home-content.ts
INSERT INTO portfolio_projects (
  legacy_id,
  slug,
  name,
  description,
  full_description,
  image_url,
  fallback_image_url,
  client,
  year,
  project_url,
  technologies,
  features,
  show_on_homepage,
  homepage_featured,
  homepage_tags,
  homepage_preview,
  homepage_sort_order,
  sort_order,
  published
) VALUES
(
  16,
  'magia-podrozowania',
  'Magia Podróżowania',
  'Kompleksowy system CRM do zarządzania wycieczkami - rezerwacje, płatności PayNow, umowy PDF i integracje z SaldeoSMART oraz HDI.',
  'Magia Podróżowania to kompleksowy system CRM do zarządzania wycieczkami dla organizatora turystyki GRUPA DE-PL. Aplikacja obejmuje cały cykl obsługi wycieczki - od tworzenia oferty, przez rezerwacje online i płatności, aż po generowanie umów, faktur i ubezpieczeń.

System obejmuje panel organizatora, publiczne strony wycieczek z rezerwacją online, płatności PayNow z podziałem na raty, edytor umów PDF, integrację SaldeoSMART i HDI, komunikację e-mail SMTP oraz panel koordynatora wycieczek.',
  '/magia-podrozowania.png',
  '/placeholder.svg?height=600&width=400',
  'GRUPA DE-PL / Magia Podróżowania',
  2025,
  'https://mainly.pl/projekty/magia-podrozowania',
  ARRAY['Next.js', 'React', 'TypeScript', 'Supabase', 'PayNow', 'Tailwind CSS'],
  ARRAY['Panel organizatora wycieczek', 'Rezerwacje online z płatnościami PayNow', 'Generowanie umów i faktur PDF', 'Integracja SaldeoSMART i HDI', 'Moduł koordynatora wycieczek', 'Komunikacja e-mail z uczestnikami'],
  true,
  true,
  ARRAY['CRM', 'PayNow', 'Next.js', '2025'],
  'featured',
  1,
  16,
  true
),
(
  15,
  'akademia-wiedzy',
  'Akademia Wiedzy',
  'System e-korepetycji dla 40+ korepetytorów i 865+ uczniów - automatyczne lekcje, rozliczenia i płatności PayU.',
  'Akademia Wiedzy to firma e-korepetycyjna prowadząca zajęcia online dla uczniów w całej Polsce - ponad 40 korepetytorów i 865+ uczniów. Zbudowałem wewnętrzny system webowy, który zastąpił ręczne zarządzanie grafikami, uczniami i rozliczeniami.

Aplikacja automatyzuje planowanie lekcji, oferuje panel korepetytora i administratora, publiczny kalendarz rezerwacji dla nowych uczniów, moduł rozliczeń z linkami PayU oraz architekturę Row Level Security w Supabase.',
  '/akademia-wiedzy.png',
  '/placeholder.svg?height=600&width=400',
  'Akademia Wiedzy - Kamil Miącz',
  2026,
  'https://akademia-kamilmiacz.pl/',
  ARRAY['Next.js', 'TypeScript', 'Supabase', 'PayU', 'Tailwind CSS'],
  ARRAY['Automatyczne generowanie lekcji', 'Panel korepetytora i administratora', 'Publiczny kalendarz rezerwacji', 'Rozliczenia i płatności PayU', 'Row Level Security', '865+ uczniów, 40+ korepetytorów'],
  true,
  false,
  ARRAY['System e-korepetycji', 'PayU', '2026'],
  'akademia',
  3,
  15,
  true
),
(
  14,
  'airset-platforma',
  'Platforma Szkoleniowa AIRSET',
  'Dedykowany system e-learningowy dla linii lotniczych - szkolenia, testy, raporty i logi audytu z Supabase RLS.',
  'Platforma Szkoleniowa AIRSET to dedykowany system e-learningowy dla linii lotniczych AIRSET. Obejmuje publikowanie szkoleń z materiałami PDF, PPTX i PNG, kreator testów z sześcioma typami pytań, dashboard postępów, zarządzanie użytkownikami z rolami, raporty miesięczne (PDF, CSV, XLSX) oraz kompleksowe logi audytowe.

Bezpieczeństwo oparte jest na Row Level Security - każde zapytanie respektuje uprawnienia użytkownika.',
  '/airset-platforma.png',
  '/placeholder.svg?height=600&width=400',
  'AIRSET',
  2025,
  'https://airset.pl/',
  ARRAY['Next.js', 'TypeScript', 'Supabase', 'Tailwind CSS', 'shadcn/ui'],
  ARRAY['Kreator testów (6 typów pytań)', 'Dashboard postępów szkoleń', 'Zarządzanie użytkownikami i rolami', 'Raporty PDF, CSV, XLSX', 'Logi audytowe', 'Row Level Security'],
  true,
  false,
  ARRAY['E-learning', 'Supabase RLS', '2025'],
  'airset',
  2,
  14,
  true
),
(
  13,
  'elomoto-eco',
  'Elomoto.eco',
  'SPA dla operatora stacji ładowania EV - 15+ podstron, interaktywna mapa i widget ładowania 0-77 kWh.',
  'Responsywna aplikacja SPA dla polskiego operatora infrastruktury ładowania pojazdów elektrycznych Elomoto (ekosystem Energomix). Projekt obejmuje ponad 15 podstron - od landing page''a, przez podstrony ofertowe i mapę stacji, po blog, FAQ i formularz kontaktowy.

Wyróżniający element to interaktywny widget ładowania reagujący na scroll (0-77 kWh), ciemny motyw z glassmorphism oraz routing SPA bez przeładowań.',
  '/placeholder.svg?height=600&width=800',
  '/placeholder.svg?height=600&width=400',
  'Elomoto Sp. z o.o. (Energomix)',
  2025,
  'https://elomoto.eco/',
  ARRAY['React', 'TypeScript', 'Vite', 'Tailwind CSS'],
  ARRAY['15+ podstron ofertowych', 'Interaktywna mapa stacji EV', 'Widget ładowania 0-77 kWh', 'Routing SPA bez przeładowań', 'Ciemny motyw z glassmorphism', 'Blog, FAQ, formularz kontaktowy'],
  false,
  false,
  '{}',
  NULL,
  NULL,
  13,
  true
),
(
  12,
  'biblioteka-promptow',
  'Biblioteka Promptów AI',
  'Polskojęzyczna platforma z ponad 1000 gotowych promptów dla ChatGPT, Claude, Midjourney i innych narzędzi AI',
  'Biblioteka Promptów to polskojęzyczna platforma internetowa oferująca ponad 1000 gotowych, szablonowych promptów (poleceń) do popularnych narzędzi sztucznej inteligencji. Projekt ma na celu ułatwić pracę z narzędziami AI, dostarczając sprawdzone prompty, które oszczędzają czas i poprawiają jakość wyników. Platforma obsługuje najpopularniejsze narzędzia AI: ChatGPT (OpenAI), Claude (Anthropic), Gemini (Google), Midjourney, DALL·E oraz Stable Diffusion. Prompty są zorganizowane w sekcje: prompty tekstowe (dla chatbotów i asystentów AI) oraz prompty graficzne (dla narzędzi do generowania obrazów), podzielone na 15+ kategorii tematycznych obejmujących marketing, copywriting, programowanie, analizę danych biznesowych, content creation na social media i inne specjalistyczne obszary. Wszystkie prompty są całkowicie darmowe i mogą być używane zarówno do celów osobistych, jak i komercyjnych.',
  '/biblioteka-promptow2.png',
  '/bibliotekapromptow.png',
  'Projekt własny',
  2025,
  'https://bibliotekapromptow.pl/',
  ARRAY['Next.js', 'TypeScript', 'Tailwind CSS', 'OpenAI API', 'Claude API'],
  ARRAY['Ponad 1000 gotowych, sprawdzonych promptów', 'Obsługa ChatGPT, Claude, Gemini, Midjourney, DALL·E, Stable Diffusion', '15+ kategorii tematycznych (marketing, copywriting, programowanie, analiza danych)', 'Prompty tekstowe i graficzne w osobnych sekcjach', 'Zaawansowana wyszukiwarka umożliwiająca szybkie znalezienie promptu', 'Kopiowanie promptów jednym kliknięciem', 'Sprawdzone i przetestowane prompty gwarantujące najlepsze wyniki', 'Intuicyjny interfejs dostępny dla początkujących i zaawansowanych', 'Całkowicie darmowe - do użytku osobistego i komercyjnego', 'Responsywny design dostosowany do wszystkich urządzeń'],
  true,
  false,
  ARRAY['AI', 'Next.js', '2025'],
  'featured',
  4,
  12,
  true
),
(
  9,
  'music-pad',
  'Interaktywny Pad Muzyczny',
  'Kreatywne narzędzie do tworzenia muzyki w przeglądarce',
  'Innowacyjna aplikacja webowa umożliwiająca tworzenie muzyki w czasie rzeczywistym. Użytkownicy mogą komponować własne utwory wykorzystując 16 programowalnych padów z różnymi trybami odtwarzania (normalny, pulsujący, ciągły). Aplikacja oferuje bogaty wybór instrumentów i melodii, zaawansowaną wizualizację dźwięku oraz możliwość nagrywania sesji. Intuicyjne sterowanie za pomocą klawiatury oraz interaktywny interfejs sprawiają, że tworzenie muzyki staje się dostępne dla każdego.',
  '/musicpad.png',
  '/placeholder.svg?height=600&width=400',
  'Projekt własny',
  2024,
  'https://musicpad-mainly.vercel.app/',
  ARRAY['Next.js', 'TypeScript', 'Tailwind CSS', 'Web Audio API', 'Tone.js'],
  ARRAY['16 programowalnych padów muzycznych', 'Trzy tryby odtwarzania dźwięków', 'Biblioteka instrumentów i melodii', 'Wizualizacja fali dźwiękowej', 'System nagrywania i eksportu do MP3', 'Sterowanie za pomocą klawiatury', 'Interaktywny interfejs użytkownika', 'Responsywny design'],
  false,
  false,
  '{}',
  NULL,
  NULL,
  9,
  true
),
(
  8,
  'lease1-leasing',
  'Lease1 - Partner Leasingowy',
  'Platforma dla globalnego partnera leasingowego',
  'Nowoczesna platforma internetowa dla firmy Lease1, specjalizującej się w kompleksowych rozwiązaniach leasingowych na skalę międzynarodową. Strona oferuje przejrzystą prezentację różnych form leasingu (maszyn, samochodów, nieruchomości) wraz z intuicyjnym procesem składania wniosków. Zaimplementowano wielojęzyczność (PL, EN, DE) oraz zaawansowany system kalkulatorów leasingowych. Projekt wyróżnia się profesjonalnym designem i płynną ścieżką użytkownika od pierwszego kontaktu do finalizacji umowy.',
  '/lease1.png',
  '/placeholder.svg?height=600&width=400',
  'Lease1',
  2024,
  'https://lease1.pl',
  ARRAY['Next.js', 'TypeScript', 'Shadcn/ui', 'Tailwind CSS', 'i18n'],
  ARRAY['System wielojęzyczności (PL, EN, DE)', 'Kalkulatory leasingowe', 'Interaktywne formularze wniosków', 'Panel klienta', 'Prezentacja ofert leasingowych', 'Blog z poradami finansowymi', 'Moduł FAQ z wyszukiwarką', 'Responsywny design dostosowany do wszystkich urządzeń'],
  false,
  false,
  '{}',
  NULL,
  NULL,
  8,
  true
),
(
  7,
  'bcsc-ksiegowosc',
  'Business Care SC',
  'Nowoczesna strona dla biura księgowego specjalizującego się w startupach',
  'Profesjonalna strona internetowa dla biura księgowego Business Care SC, zaprojektowana z myślą o startupach i młodych firmach. Strona charakteryzuje się nowoczesnym designem, przejrzystą prezentacją usług oraz intuicyjną nawigacją. Zaimplementowano system formularzy kontaktowych, automatyczne kalkulatory oraz sekcję z opiniami klientów. Projekt wyróżnia się elegancką typografią, spójną kolorystyką oraz płynną responsywnością na wszystkich urządzeniach.',
  '/bcsc.png',
  '/placeholder.svg?height=600&width=400',
  'Business Care SC',
  2024,
  'https://bcsc.pl',
  ARRAY['Next.js', 'TypeScript', 'Shadcn/ui', 'Tailwind CSS'],
  ARRAY['Nowoczesny, responsywny design', 'Interaktywne formularze kontaktowe', 'Sekcja opinii klientów', 'Automatyczne kalkulatory wycen', 'Blog z poradami księgowymi', 'Optymalizacja SEO', 'System CMS do zarządzania treścią'],
  false,
  false,
  '{}',
  NULL,
  NULL,
  7,
  true
),
(
  6,
  'generator-ofert-rolety',
  'Generator Ofert Rolety3miasto',
  'System automatyzacji wycen i generowania ofert dla firmy roletowej',
  'Zaawansowane narzędzie do tworzenia spersonalizowanych ofert dla klientów firmy Rolety3miasto. System umożliwia błyskawiczne kalkulacje cen na podstawie wybranych parametrów, automatycznie generuje profesjonalne dokumenty PDF z ofertą, uwzględniając wszystkie specyfikacje techniczne i preferencje klienta. Dzięki temu rozwiązaniu firma może szybko przedstawić dokładną i profesjonalną wycenę dostosowaną do indywidualnych potrzeb każdego klienta.',
  '/rolety-generator.png',
  '/placeholder.svg?height=600&width=400',
  'Rolety3miasto',
  2024,
  'https://oferty.rolety3miasto.pl',
  ARRAY['Next.js', 'TypeScript', 'Shadcn/ui', 'React PDF', 'Tailwind CSS'],
  ARRAY['Automatyczne kalkulacje cenowe', 'Generowanie spersonalizowanych ofert PDF', 'Zarządzanie bazą produktów i materiałów', 'Konfiguracja różnych wariantów produktów', 'System rabatów i promocji', 'Eksport danych do różnych formatów'],
  false,
  false,
  '{}',
  NULL,
  NULL,
  6,
  true
),
(
  5,
  'kreator-faktur',
  'Kreator Faktur',
  'Intuicyjne narzędzie do generowania faktur VAT',
  'Nowoczesna aplikacja webowa do tworzenia i zarządzania fakturami. Umożliwia szybkie generowanie profesjonalnych faktur VAT w formacie PDF z możliwością personalizacji. System oferuje automatyczne obliczenia, zarządzanie kontrahentami oraz eksport dokumentów.',
  '/faktury.png',
  '/placeholder.svg?height=600&width=400',
  'Projekt własny',
  2024,
  'https://faktury.mainly.pl',
  ARRAY['Next.js', 'TypeScript', 'React PDF', 'Tailwind CSS'],
  ARRAY['Generowanie faktur VAT w PDF', 'Automatyczne obliczenia podatku', 'Zarządzanie bazą kontrahentów', 'Personalizacja szablonów faktur', 'Eksport do różnych formatów', 'Intuicyjny interfejs użytkownika'],
  false,
  false,
  '{}',
  NULL,
  NULL,
  5,
  true
),
(
  4,
  'audiogen',
  'Audiogen',
  'System automatyzacji zbierania leadów dla startupu',
  'Strona typu landing page dla innowacyjnego startupu Audiogen, specjalizującego się w tworzeniu audiobooków. Projekt obejmował stworzenie systemu automatycznego zbierania i zarządzania bazą potencjalnych klientów poprzez formularz zapisu na whitelistę. Zaimplementowano zaawansowaną automatyzację procesu wraz z systemem powiadomień.',
  '/audiogen.png',
  '/placeholder.svg?height=600&width=400',
  'Audiogen',
  2024,
  'https://audiogen.framer.website',
  ARRAY['Framer', 'React', 'TypeScript', 'Automation'],
  ARRAY['System zapisu na whitelistę', 'Automatyzacja zbierania leadów', 'Integracja z systemem mailingowym', 'Responsywny design', 'Animacje i efekty interaktywne'],
  false,
  false,
  '{}',
  NULL,
  NULL,
  4,
  true
),
(
  1,
  'kalkulator-gap',
  'Kalkulator GAP',
  'Kalkulator ubezpieczeniowy z intuicyjnym interfejsem',
  'Kompleksowe narzędzie do obliczania ubezpieczenia GAP z intuicyjnym interfejsem użytkownika. Projekt obejmował pełen proces UX/UI oraz front-end development. Kalkulator umożliwia precyzyjne wyliczenia kosztów ubezpieczenia GAP z uwzględnieniem wszystkich niezbędnych parametrów.',
  '/kalkulator2.png',
  '/placeholder.svg?height=600&width=400',
  'Firma Ubezpieczeniowa Business Care',
  2025,
  'https://gapauto.pl',
  ARRAY['Next.js', 'Shadcn', 'React', 'TypeScript', 'Tailwind CSS'],
  ARRAY['Intuicyjny interfejs użytkownika', 'Responsywny design', 'Zaawansowane algorytmy kalkulacyjne', 'Integracja z API ubezpieczeniowym'],
  false,
  false,
  '{}',
  NULL,
  NULL,
  1,
  true
),
(
  2,
  'cytomania',
  'Cytomania',
  'Portal z cytatami filmowymi',
  'Społecznościowy portal gromadzący cytaty z filmów i seriali. Użytkownicy mogą dodawać, oceniać i komentować cytaty oraz tworzyć własne kolekcje. Portal oferuje zaawansowaną wyszukiwarkę, system oceniania oraz moduł administratora do zarządzania treścią.',
  '/cytomania1.png',
  '/placeholder.svg?height=600&width=400',
  'Grupa facebookowa Cytaty filmowe',
  2024,
  'https://cytomania.pl',
  ARRAY['Next.js', 'Shadcn', 'React', 'TypeScript', 'Tailwind CSS'],
  ARRAY['System użytkowników i kont', 'Wyszukiwarka cytatów', 'System oceniania i komentarzy', 'Personalizowane kolekcje cytatów', 'Moduł administratora'],
  false,
  false,
  '{}',
  NULL,
  NULL,
  2,
  true
),
(
  3,
  'kulio-studio',
  'Kulio Studio',
  'Agencja marketingowa',
  'Strona internetowa dla agencji marketingowej Kulio Studio. Projekt obejmował kompleksowy design, development oraz system CMS do zarządzania portfolio i blogiem. Strona prezentuje portfolio projektów agencji, zawiera sekcję blogową oraz formularz kontaktowy.',
  '/kulio2.png',
  '/placeholder.svg?height=600&width=400',
  'Kulio Studio',
  2024,
  'https://kuliostudio.pl',
  ARRAY['Framer', 'Spline'],
  ARRAY['Portfolio projektów', 'System blogowy', 'Formularz kontaktowy', 'Integracja z mediami społecznościowymi', 'Panel administracyjny'],
  false,
  false,
  '{}',
  NULL,
  NULL,
  3,
  true
),
(
  10,
  'milei-coin',
  'Coin Milei',
  'Dynamiczna strona one-pager dla kryptowaluty $MILEI inspirowanej Javierem Milei.',
  'Dynamiczna strona one-pager dla kryptowaluty $MILEI inspirowanej Javierem Milei. Strona prezentuje token oparty na ideologii libertariańskiej, łączący memecoin z komentarzem polityczno-ekonomicznym. Projekt obejmował pełny design i wdrożenie we Framerze, integrację wykresu TradingView, dynamicznych tweetów z Twittera/X, sekcji partnerów oraz liczników statystyk.',
  '/milei.png',
  '/placeholder.svg?height=600&width=400',
  'Projekt komercyjny (Web3/Crypto)',
  2024,
  'https://milei.framer.ai/',
  ARRAY['Framer', 'TradingView', 'Twitter/X embed', 'SVG', 'Responsywny design'],
  ARRAY['Sekcja Hero z AI-generowanym portretem Javiera Milei i CTA', 'Osadzony wykres TradingView kursu $MILEI', 'Interaktywne karty funkcjonalności tokena (tokenomics, decentralizacja, memiczność)', 'Instrukcja zakupu (iOS/Android)', 'Sekcja partnerów (Telegram, CoinMarketCap, Uniswap)', 'Dynamiczne statystyki: licznik czasu, liczba holderów, tokenów, liquidity', 'Wbudowane tweety z Twittera/X', 'Opis ideologii tokena i motywów politycznych', 'Pełna responsywność i optymalizacja UX', 'Szybkość ładowania (SVG, brak backendu)', 'Animacje i mikrointerakcje w stylu Framera'],
  false,
  false,
  '{}',
  NULL,
  NULL,
  10,
  true
),
(
  11,
  'prawkoczechy',
  'Prawo Jazdy w Czechach',
  'Strona dla firmy świadczącej usługi zdawania egzaminów na prawo jazdy w Czechach, zintegrowana z Google Ads i zoptymalizowana pod kątem konwersji.',
  'Strona internetowa dla firmy oferującej kompleksowe usługi związane z egzaminami na prawo jazdy w Czechach. W ramach współpracy zapewniliśmy nie tylko nowoczesny design i responsywność, ale również wsparcie w zakresie Google Ads oraz optymalizację pod kątem maksymalizacji konwersji. Strona została zaprojektowana tak, aby przyciągać potencjalnych klientów i zachęcać ich do kontaktu.',
  '/prawkoczechy.png',
  '/placeholder.svg?height=600&width=400',
  'Prawo Jazdy w Czechach',
  2024,
  'https://www.prawkoczechy.pl/',
  ARRAY['Next.js', 'TypeScript', 'Tailwind CSS', 'Google Ads', 'SEO'],
  ARRAY['Responsywny design', 'Integracja z Google Ads', 'Optymalizacja pod kątem konwersji', 'Szybki czas ładowania', 'Intuicyjna nawigacja', 'Formularz kontaktowy', 'Sekcja FAQ', 'Testimonials'],
  false,
  false,
  '{}',
  NULL,
  NULL,
  11,
  true
)
ON CONFLICT (slug) DO UPDATE SET
  legacy_id = EXCLUDED.legacy_id,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  full_description = EXCLUDED.full_description,
  image_url = EXCLUDED.image_url,
  fallback_image_url = EXCLUDED.fallback_image_url,
  client = EXCLUDED.client,
  year = EXCLUDED.year,
  project_url = EXCLUDED.project_url,
  technologies = EXCLUDED.technologies,
  features = EXCLUDED.features,
  show_on_homepage = EXCLUDED.show_on_homepage,
  homepage_featured = EXCLUDED.homepage_featured,
  homepage_tags = EXCLUDED.homepage_tags,
  homepage_preview = EXCLUDED.homepage_preview,
  homepage_sort_order = EXCLUDED.homepage_sort_order,
  sort_order = EXCLUDED.sort_order,
  published = EXCLUDED.published,
  updated_at = now();
